server:
  port: 8088

spring:
  webflux:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/kakaobanktest
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      use-new-id-generator-mappings: false
    show-sql: true

bearer:
  headerstring: KakaoAK
  issuancekey: 0606458087ba27b68f726181e3a79be3

#sql 로깅 설정
logging:
  level:
    root: debug
    org:
      hibernate:
        SQL: DEBUG